//Generated for Decodeforce programming test
public class RegionOfficeController{

	public static map<String, String> getRegionalOfficeMapping(){

		Map<String, String> RegionOfficeMap = new Map <String, String>();

		RegionOfficeMap.put('Europe','Germany');
        RegionOfficeMap.put('Asia','India');
        RegionOfficeMap.put('North America','USA');
        RegionOfficeMap.put('South America','Brazil');



		return RegionOfficeMap;
	
	}
}